### 2025-09-24

#### Numpy

In [2]:
import numpy as np

In [3]:
L = range(1000)
%timeit L2 = [i**2 for i in L]

40.5 μs ± 1.03 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
arr = np.arange(1000)
%timeit arr2 = arr**2

872 ns ± 20.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
alist = [1, 2, 3, 4, 5, 6]
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [6]:
blist = [1, 2, None, 4, 5, 6]

In [8]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
ar1.dtype

dtype('int64')

In [11]:
ar2 = np.array([1.1, 2.2, 3.3])

In [12]:
ar2

array([1.1, 2.2, 3.3])

In [13]:
ar2.dtype

dtype('float64')

In [14]:
list_data = [1, 2., 3]

ar3 = np.array(list_data)

print(ar3)
print(ar3.dtype)

[1. 2. 3.]
float64


In [15]:
np.array([1, 2, np.nan, 4])

array([ 1.,  2., nan,  4.])

In [16]:
arr1 = np.array([1, 2, 3, 4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [17]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [18]:
arr3 = arr2.reshape(-1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [19]:
arr3 = arr2.reshape(2, -1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [21]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [23]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [24]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)


[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [31]:
a= np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2*a + b)
print(a == 2)
print(b > 10)
print((a==2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [73]:
alist = [[0, 1, 2], [3, 4, 5]]

print(alist[0][0], 
alist[0][1], 
alist[1][2])
print(alist)

0 1 5
[[0, 1, 2], [3, 4, 5]]


In [54]:
print(alist[0][:2])
print(alist[1][1:])
print([alist[0][1], alist[1][1]])

[0, 1]
[4, 5]
[1, 4]


In [57]:
blist = np.array([[0, 1, 2], [3, 4, 5]])

blist

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
print(blist[0][0], blist[0][1], blist[1][2])

0 1 5


In [61]:
print(blist[0,0], blist[0,1], blist[1,2])

0 1 5


In [70]:
print(blist[0, :2])
print(blist[-1, 1:])
print(blist[:, 1])

[0 1]
[4 5]
[1 4]


In [83]:
clist = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

clist

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
print(clist[:, :3])
print(clist[-2:, -2:])
print(clist[:, -2].reshape(3,1))

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 6  7]
 [10 11]]
[[ 2]
 [ 6]
 [10]]


In [94]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [97]:
a = np.array([1,1,2,3,4,5,6,7,8,9])
idx = [0, 2, 5]
a[idx]

array([1, 2, 5])

In [98]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
print(b[[0, 2]])

[[1 2 3]
 [7 8 9]]


In [ ]:
b[[0,1,2], [1,2,0]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
a = np.array([0,1,2,3,4,5,6,7,8,9])


print(a[a%2==0])

[0 2 4 6 8]


In [112]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [129]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [131]:
data = np.array([1, 4, 9 ,16])

In [133]:
np.sqrt(data)

array([1., 2., 3., 4.])

In [134]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [135]:
np.sum(data)

np.int64(30)

In [137]:
np.mean(data)

np.float64(7.5)

In [138]:
np.std(data)

np.float64(5.678908345800274)

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])


print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0) & (x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


#### Pandas

In [148]:
!pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 5.0 MB/s eta 0:00:03
   - -------------------------------------- 0.5/11.3 MB 5.6 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/11.3 MB 5.4 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.3 MB 5.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.3 MB 6.2 MB/s eta 0:00:02
   ----- ---------------------------------- 1.5/11.3 MB 5.9 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/11.3 MB 6.1 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.3 MB 6.2 MB/s eta 0:00:02
   -------- ------------------------------- 2.5/11.3 MB 6.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.8/11.3 MB 6.3 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/11.3 MB 6.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/11.3 MB 6.3 MB/s eta 0:00:02
   ---


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [149]:
import pandas as pd

In [156]:
df = pd.read_csv("heroes(in).csv")
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [154]:
pd.options.display.float_format = '{:.0f}'.format

In [155]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [161]:
df.describe()

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [159]:
df.head()

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [165]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [167]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [169]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [170]:
df['나이']

0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64

In [171]:
df['나이'].nlargest

<bound method Series.nlargest of 0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64>

In [172]:
df['나이'].nsmallest

<bound method Series.nsmallest of 0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64>

In [173]:
df.nlargest(7, '나이')

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000
3   원더우먼  27     공주  데미스키라  178            NaN
5   캡틴마블  25    파일럿     미국  170      340000000
2  스파이더맨  18   고등학생     미국  177            600

In [175]:
df.nlargest(7, '키')

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270     1000000000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11500000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [176]:
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [179]:
df[3:]

이름  나이     직업     국적    키         재산
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [180]:
df.iloc, df.loc

(<pandas.core.indexing._iLocIndexer at 0x1bbf87fb3e0>,
 <pandas.core.indexing._LocIndexer at 0x1bbfb3c85f0>)

In [181]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [188]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [190]:
df.iloc[[1, 3, 6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [198]:
df.iloc[0:5, 0:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [199]:
df.loc[2]

이름    스파이더맨
나이       18
직업     고등학생
국적       미국
키       177
재산      600
Name: 2, dtype: object

In [200]:
df.loc[:2, ['이름', '직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [201]:
df.loc[3:, '국적':'재산']

국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [202]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [203]:
df[df['나이'] > 30]

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [212]:
# 나이가 30초과이면서 50미만인 사람들의 전체 레코드
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [213]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [221]:
# 키가 180이상인 레코드의 이름과 나이 컬럼만 출력

df.loc[df["키"] >= 180, ["이름", "나이", "키"]]

이름  나이    키
1  토르  45  190
4  헐크  33  270

In [239]:
df['전투력'] = 98

df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   98
1     토르  45      신  아스가르드  190            NaN   98
2  스파이더맨  18   고등학생     미국  177            600   98
3   원더우먼  27     공주  데미스키라  178            NaN   98
4     헐크  33  핵물리학자     미국  270     1000000000   98
5   캡틴마블  25    파일럿     미국  170      340000000   98
6  블랙위도우  32    스파이    러시아  170       50000000   98

In [240]:
df["전투력"] = df["전투력"] - 5

df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [269]:
df.drop(columns = ['전투력'])

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  36    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [242]:
df["재산"].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [243]:
df[df["재산"].isnull()]

이름  나이  직업     국적    키  재산  전투력
1    토르  45   신  아스가르드  190 NaN   93
3  원더우먼  27  공주  데미스키라  178 NaN   93

In [244]:
df.isnull().sum()

이름     0
나이     0
직업     0
국적     0
키      0
재산     2
전투력    0
dtype: int64

In [254]:
df["재산"].fillna(df["재산"].mean())

0   11500000000000
1    2300278000120
2              600
3    2300278000120
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [255]:
df.fillna(method = 'ffill')

C:\Users\EL20\AppData\Local\Temp\ipykernel_14948\1145651979.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')


이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190 11500000000000   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            600   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [256]:
df.iloc[5, 1] = np.nan

df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블 NaN    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [285]:
# 나이의 평균값으로 결측치를 채워주세요

df["나이"] = df["나이"].fillna(df["나이"].mean())

df

이름  나이     직업     국적              키             재산  전투력
0   아이언맨  58    CEO     미국  174cmcmcmcmcm 11500000000000   93
1     토르  45      신  아스가르드  190cmcmcmcmcm            NaN   93
2  스파이더맨  18   고등학생     미국  177cmcmcmcmcm            600   93
3   원더우먼  27     공주  데미스키라  178cmcmcmcmcm            NaN   93
4     헐크  33  핵물리학자     미국  270cmcmcmcmcm     1000000000   93
5   캡틴마블  36    파일럿     미국  170cmcmcmcmcm      340000000   93
6  블랙위도우  32    스파이    러시아  170cmcmcmcmcm       50000000   93

In [270]:
df.info

<bound method DataFrame.info of       이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  36    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93>

In [284]:
def add_cm(height):
    return str(height) + 'cm'

df['키'] = df['키'].apply(add_cm)
df

이름  나이     직업     국적              키             재산  전투력
0   아이언맨  58    CEO     미국  174cmcmcmcmcm 11500000000000   93
1     토르  45      신  아스가르드  190cmcmcmcmcm            NaN   93
2  스파이더맨  18   고등학생     미국  177cmcmcmcmcm            600   93
3   원더우먼  27     공주  데미스키라  178cmcmcmcmcm            NaN   93
4     헐크  33  핵물리학자     미국  270cmcmcmcmcm     1000000000   93
5   캡틴마블  36    파일럿     미국  170cmcmcmcmcm      340000000   93
6  블랙위도우  32    스파이    러시아  170cmcmcmcmcm       50000000   93

In [287]:
df = pd.read_csv('heroes(in).csv')

In [292]:
def add_cm(height):
    return str(height) + 'cm'

def remove_cm(b):
    part = b.replace("cmcmcm", '')

    part_float = float(part)

    return str(part_float) + 'cm'

df['키'] = df['키'].apply(remove_cm)
# df['키'] = df['키'].apply(add_cm)
df

이름  나이     직업     국적        키             재산
0   아이언맨  58    CEO     미국  174.0cm 11500000000000
1     토르  45      신  아스가르드  190.0cm            NaN
2  스파이더맨  18   고등학생     미국  177.0cm            600
3   원더우먼  27     공주  데미스키라  178.0cm            NaN
4     헐크  33  핵물리학자     미국  270.0cm     1000000000
5   캡틴마블  25    파일럿     미국  170.0cm      340000000
6  블랙위도우  32    스파이    러시아  170.0cm       50000000

In [293]:
df.groupby('국적')['나이'].mean()

국적
데미스키라   27
러시아     32
미국      34
아스가르드   45
Name: 나이, dtype: float64