### 2025-09-24

#### Numpy

In [2]:
import numpy as np

In [3]:
L = range(1000)
%timeit L2 = [i**2 for i in L]

40.5 μs ± 1.03 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
arr = np.arange(1000)
%timeit arr2 = arr**2

872 ns ± 20.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
alist = [1, 2, 3, 4, 5, 6]
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [6]:
blist = [1, 2, None, 4, 5, 6]

In [8]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
ar1.dtype

dtype('int64')

In [11]:
ar2 = np.array([1.1, 2.2, 3.3])

In [12]:
ar2

array([1.1, 2.2, 3.3])

In [13]:
ar2.dtype

dtype('float64')

In [14]:
list_data = [1, 2., 3]

ar3 = np.array(list_data)

print(ar3)
print(ar3.dtype)

[1. 2. 3.]
float64


In [15]:
np.array([1, 2, np.nan, 4])

array([ 1.,  2., nan,  4.])

In [16]:
arr1 = np.array([1, 2, 3, 4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [17]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [18]:
arr3 = arr2.reshape(-1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [19]:
arr3 = arr2.reshape(2, -1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [21]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [23]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [24]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)


[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [31]:
a= np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2*a + b)
print(a == 2)
print(b > 10)
print((a==2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [73]:
alist = [[0, 1, 2], [3, 4, 5]]

print(alist[0][0], 
alist[0][1], 
alist[1][2])
print(alist)

0 1 5
[[0, 1, 2], [3, 4, 5]]


In [54]:
print(alist[0][:2])
print(alist[1][1:])
print([alist[0][1], alist[1][1]])

[0, 1]
[4, 5]
[1, 4]


In [57]:
blist = np.array([[0, 1, 2], [3, 4, 5]])

blist

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
print(blist[0][0], blist[0][1], blist[1][2])

0 1 5


In [61]:
print(blist[0,0], blist[0,1], blist[1,2])

0 1 5


In [70]:
print(blist[0, :2])
print(blist[-1, 1:])
print(blist[:, 1])

[0 1]
[4 5]
[1 4]


In [83]:
clist = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

clist

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
print(clist[:, :3])
print(clist[-2:, -2:])
print(clist[:, -2].reshape(3,1))

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 6  7]
 [10 11]]
[[ 2]
 [ 6]
 [10]]


In [94]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [97]:
a = np.array([1,1,2,3,4,5,6,7,8,9])
idx = [0, 2, 5]
a[idx]

array([1, 2, 5])

In [98]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
print(b[[0, 2]])

[[1 2 3]
 [7 8 9]]


In [ ]:
b[[0,1,2], [1,2,0]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
a = np.array([0,1,2,3,4,5,6,7,8,9])


print(a[a%2==0])

[0 2 4 6 8]


In [112]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [129]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])